# Base configs
baseurl: "https://Arjun-Dogra.github.io/Photography/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Arjun Dogra"
subtitle: "Clickety click click!"
author: "Arjun Dogra"
header:
 title: "Photography"
 subtitle: "by Arjun Dogra"
footer:
 name: "Hey there, my name is Arjun"
 bio: "I am a developer and a tech aficionado from India. Love making teeny tiny apps solving tiny problems in life and now learning photography."
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
web_design: "AJ"
social_urls:
  instagram: "https://www.instagram.com/they.cant.say.cheese/"
  github: "https://arjun-dogra.github.io/Photography/"
